version: '3'
services:

  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: python:3.9-stretch
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "false"
      APP_PORT: 5000
    volumes:
      - appdata:/var/www
    networks:
      - frontend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "8181:8181"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

  appvue:
    build:
      context: front
      dockerfile: Dockerfile
    container_name: appvue
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      APP_VUE_ROOT_API: "http://localhost:8181"
    ports:
      - "80:80"
    volumes:
      - appvuedata:/data/app
    depends_on:
      - flask
    networks: 
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
  appvuedata:
    driver: local